VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "DataHeader"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit


 Public Units As String
 Public DTMType As String
 Public DTM As String
 Public NumberOfReaches
 Public NumberOfCrossSection
 Public MapProjection As String
 Public Datum As String

